stages: 
  - stage: continuous_integration
    jobs: 
    - job: dotnet build
      
      steps:
      - script: dotnet restore          
      - script: dotnet build       
      - script: dotnet test      
      - script: dotnet publish
        
         
      