#creating build pipeline for dotnet app
stages: 
   - stage: continuousintegration
     jobs: 
     - job: dotnetbuild
       steps:
       - script: dotnet restore
       - script: dotnet build
       - script: dotnet test
       - script: dotnet publish
         

        
